name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
              
  - type: checkboxes
    id: before
    attributes:
      label: Before You Report
      description: Following these steps first gives us the best chance of fixing your problem.
      options:
        - label: My mods and Everest install are up to date.
          required: false
        - label: I have recreated the bug with a minimum number of mods installed.
          required: false
          
  - type: input
    id: platform
    attributes:
      label: What platform are you playing on?
      description: e.g. Windows 10 FNA, Mac, Linux, etc.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Bug Description
      description: What happened? And what did you expect to happen?
      value: "Please give a clear and concise description of the bug."
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How do we trigger this bug ourselves?
      value: "Attach screenshots, video, a map, etc. as needed."
    validations:
      required: true
                    
  - type: textarea
    id: log
    attributes:
      label: Log Output
      description: Please copy and paste any relevant log output.
      render: shell
